kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: orleans
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "PUT", "DELETE"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding-orleans
subjects:
- kind: ServiceAccount
  name: orleans
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterversions-access
rules:
- apiGroups: ["orleans.dot.net"]
  resources: ["clusterversions"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["orleans.dot.net"]
  resources: ["silos"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterversions-access-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: orleans
roleRef:
  kind: ClusterRole
  name: clusterversions-access
  apiGroup: rbac.authorization.k8s.io
